### ISSUE TITLE
Cube dissociates

### ISSUE THREAD

**Issue by ineiti** [ndavd/ncube#10]
I'm not sure this is a bug, but I'm quite certain :)

If you take a 5-dimensional cube, and let it rotate on q1q4, q2q3, and q3q4, after some rotations, the cube gets very much out of shape.

As I said: not 100% sure, but it really looks stranger to me than what a 5d cube should look like.

**Comment by ndavd** [comment]
I'll take a better look but it sounds normal. It might happen because we're looking at a shadow of a shadow of a shadow, etc... So sometimes the projections add up and that makes it grow more and more. I'm not sure how to mitigate that, seems like a natural thing but at the same time it doesn't look pleasant. Perhaps playing with the projection factors... But needs investigation

**Comment by ineiti** [comment]
I thought it might also be an accumulation of rounding errors. Depending on how you calculate the movement of your 5D cube, some errors might add up.

At least the examples I could find do not break out of the box :)

https://www.reddit.com/r/Python/comments/gx67cu/do_you_know_what_a_5d_cube_is_like_lets_rotate_it/

**Comment by ndavd** [comment]
That's definitely possible. I will investigate it. Thanks for pointing it out!
I'll give an update soon.

**Comment by ndavd** [comment]
Definitely a floating-point error! :)
![image](https://github.com/ndavd/ncube/assets/74260683/cd7633e5-8731-455e-b795-f88d6c29d2fc)

**Comment by ndavd** [comment]
An update on the progress.

Made a couple big improvements to precision:
- Making all calculations in f64s as opposed to f32s
- _Correcting_ the hypercube every full rotation

However, the issue still remains. It happens when rotating in at least 2 overlapping planes and we notice a _jump_ when applying the correction... This must be something deeper.

**Comment by ineiti** [comment]
I would also look into divisions. When the denominator is between 1 and 0, this can give wrong results.

**Comment by ndavd** [comment]
The simplest broken case:
- dimensions: 3
- rotations: q0q1: 3.0, q0q2: 3.0

**Comment by ndavd** [comment]
Update: Found the bug. Bad generation of complex rotation matrices.

Now all rotations work as expected, thanks of the report. Feel free to re-open or continue the discussion here. For now I will close this as it is solved.

**Comment by ineiti** [comment]
Great! Now you just need to update the third image in the README.md.

**Comment by ndavd** [comment]
I'll check it out but it seems to behave the same. This issue only happened on rotations with intersecting planes of rotation.

**Comment by ndavd** [comment]
Behaves the same. I don't think it's a bug.
